Organizations:
  - &HartleyMember
    Name: HartleyMember
    ID: m-JTEWIZUBCNA63NJRMK3XWLU2ZQ
    MSPDir: crypto-config/memberOrganizations/n-YD3MZANHRRDA3ETFSMNQMHCMH4.managedblockchain.amazonaws.com/users/Admin@m-JTEWIZUBCNA63NJRMK3XWLU2ZQ.msp

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Policies: &ApplicationPolicies
  Readers:
    Type: ImplicitMeta
    Rule: "ANY Readers"
  Writers:
    Type: ImplicitMeta
    Rule: "ANY Writers"
  Admins:
    Type: ImplicitMeta
    Rule: "ANY Admins"

Application: &ApplicationDefaults
  Organizations:
  Policies:
    <<: *ApplicationPolicies
  Capabilities:
    <<: *ApplicationCapabilities

Profiles:
  HartleyChannel:
    Consortium: AWSSystemConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *HartleyMember